sonar.projectKey=ynov-ecommerce_ci_cd_fork
sonar.organization=buzz30gotcho
sonar.sources=.
sonar.exclusions=src/test/**, node_modules/**, coverage/**, **/*.test.js, .husky/**, .github/**
sonar.tests=src/test
sonar.test.inclusions=src/test/**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
